name: 书籍爬虫

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      # 其他步骤保持不变...
      
      - name: 验证数据库内容
        if: always()  # 无论前面步骤是否成功都执行
        run: |
          echo "检查数据库内容..."
          if [ -f "book_history.db" ]; then
            echo "数据库文件存在，查看表结构:"
            sqlite3 book_history.db ".schema books"
            
            echo "查看书籍数量:"
            sqlite3 book_history.db "SELECT COUNT(*) FROM books;"
            
            echo "查看最近添加的书籍:"
            sqlite3 book_history.db "SELECT title, publish_month, first_seen FROM books ORDER BY first_seen DESC LIMIT 5;"
          else
            echo "❌ 数据库文件不存在!"
            exit 1
          fi
