name: Book Crawler

on:
  schedule:
    - cron: '50 14 * * *'  # 每天UTC时间14:30执行（北京时间22:30）
  workflow_dispatch:  # 允许手动触发

jobs:
  crawl:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4
          
      - name: Run crawler
        env:
          SCKEY: ${{ secrets.SCKEY }}
        run: |
          python crawler.py
