name: 书籍爬虫

on:
  schedule:
    - cron: '0 4 * * *'  # 每天UTC时间4点（北京时间12点）
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies (skip if no requirements.txt)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else echo "No requirements.txt, skipping installation"; fi

      - name: Run scraper
        run: python main.py

      - name: Upload database artifact
        uses: actions/upload-artifact@v4
        with:
          name: database
          path: ./database.sqlite

  post-processing:
    needs: run-scraper
    runs-on: ubuntu-latest

    steps:
      - name: Download database artifact
        uses: actions/download-artifact@v4
        with:
          name: database
          path: ./

      - name: Post-processing
        run: |
          echo "Processing database..."
          ls -l ./database.sqlite
