name: 书籍爬虫

on:
  schedule:
    - cron: '0 11 * * *'  # 每天UTC时间4点（北京时间12点）运行
  workflow_dispatch:  # 允许手动触发

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
      
      - name: 设置Python环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4
      
      - name: 下载数据库文件（如果存在）
        uses: actions/download-artifact@v4  # 更新到v4版本
        with:
          name: database
          path: .
      
      - name: 运行爬虫
        env:
          WECHAT_WORK_WEBHOOK: ${{ secrets.WECHAT_WORK_WEBHOOK }}
          DB_DIR: .
        run: |
          python crawler.py
      
      - name: 上传数据库文件
        uses: actions/upload-artifact@v4  # 更新到v4版本
        with:
          name: database
          path: book_history.db
      
      - name: 上传日志文件
        uses: actions/upload-artifact@v4  # 更新到v4版本
        with:
          name: logs
          path: crawler.log
