name: Book Crawler

on:
  schedule:
    - cron: '30 10 * * *'  # 每天10:30执行（UTC时间）
  workflow_dispatch:  # 允许手动触发

jobs:
  crawl:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4
          
      - name: Run crawler
        env:
          SCKEY: ${{ secrets.SCKEY }}  # 从GitHub Secrets获取SCKEY
        run: |
          python crawler.py
